# Generated by Django 6.0.3 on 2026-04-28 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_conversation_ai_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ConversationMessageFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('filename', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('message', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='file', to='conversation.message')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
